# Generated by Django 3.1.5 on 2021-01-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.CharField(blank=True, default='https://picsum.photos/200/300.jpg', max_length=500),
        ),
    ]
