# Generated by Django 3.1.5 on 2021-01-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210118_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.CharField(default='https://picsum.photos/200/300.jpg', max_length=500),
        ),
    ]
